import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  FlaskConical, Dna, Atom, Activity, Wind, Leaf, 
  TestTube2, Flower2, Brain, Rocket, Magnet, Droplets, 
  Flame, Sun, Moon, Star, Microscope, Heart, Bug, Sprout, 
  Waves, Cloud, Snowflake, Home, Apple, Shield, 
  Bone, Globe, ArrowRight, 
  ArrowDown, Thermometer, Zap, Building2, Rainbow, 
  Sparkles, TreePine, Fish, Bird, Cat
} from 'lucide-react';

// --- Define Experiment ---
interface Experiment {
  id: string;
  title: string;
  icon: React.ReactNode;
  color: string;
  bgColor: string;
  description: string;
  level: number;
  steps: string[];
  conclusion: string;
}

// --- 50 BIOLOGY EXPERIMENTS ---
const BIOLOGY_EXPERIMENTS: Experiment[] = [
  { id: 'bio-1', title: 'Plant Life Cycle', icon: <Leaf className="w-8 h-8" />, color: 'text-emerald-400', bgColor: 'bg-emerald-500/10', description: 'How does a tiny seed become a big plant?', level: 1, steps: ['Place the seed in soil.', 'Water it daily.', 'Watch it sprout!', 'It grows into a plant.'], conclusion: 'Plants need soil, water, and sunlight to grow!' },
  { id: 'bio-2', title: 'My Amazing Heart', icon: <Activity className="w-8 h-8" />, color: 'text-red-400', bgColor: 'bg-red-500/10', description: 'What does your heart do all day?', level: 1, steps: ['Feel your heartbeat.', 'Run in place.', 'Feel it beat faster.', 'Take deep breaths.'], conclusion: 'Your heart pumps blood to give your body energy!' },
  { id: 'bio-3', title: '5 Senses', icon: <Dna className="w-8 h-8" />, color: 'text-yellow-400', bgColor: 'bg-yellow-500/10', description: 'How do we experience the world?', level: 1, steps: ['See a flower.', 'Hear a bird.', 'Smell a lemon.', 'Touch a soft blanket.'], conclusion: 'We learn about the world using our eyes, ears, nose, skin, and tongue!' },
  { id: 'bio-4', title: 'Living vs Non-Living', icon: <Bug className="w-8 h-8" />, color: 'text-green-400', bgColor: 'bg-green-500/10', description: 'What is alive and what is not?', level: 1, steps: ['Look at a rock.', 'Look at a dog.', 'Does the rock grow?', 'Does the dog grow?'], conclusion: 'Living things grow, eat, breathe, and move!' },
  { id: 'bio-5', title: 'Animal Habitats', icon: <Home className="w-8 h-8" />, color: 'text-teal-400', bgColor: 'bg-teal-500/10', description: 'Where do animals live?', level: 1, steps: ['A fish lives in water.', 'A lion lives in the savanna.', 'A bear lives in the woods.', 'Animals need the right home.'], conclusion: 'Animals live in places where they can find food and shelter!' },
  { id: 'bio-6', title: 'Frog Life Cycle', icon: <Bug className="w-8 h-8" />, color: 'text-cyan-400', bgColor: 'bg-cyan-500/10', description: 'From egg to frog!', level: 2, steps: ['Frog lays eggs.', 'Eggs become tadpoles.', 'Tadpoles grow legs.', 'They become frogs!'], conclusion: 'Frogs go through amazing changes as they grow!' },
  { id: 'bio-7', title: 'Butterfly Metamorphosis', icon: <Flower2 className="w-8 h-8" />, color: 'text-pink-400', bgColor: 'bg-pink-500/10', description: 'The most magical change!', level: 2, steps: ['A caterpillar eats.', 'It makes a cocoon.', 'It rests inside.', 'A butterfly emerges!'], conclusion: 'Caterpillars transform into butterflies through metamorphosis!' },
  { id: 'bio-8', title: 'Parts of a Flower', icon: <Flower2 className="w-8 h-8" />, color: 'text-purple-400', bgColor: 'bg-purple-500/10', description: 'What makes a flower a flower?', level: 2, steps: ['Petals are colorful.', 'The stem holds it up.', 'Roots drink water.', 'The flower makes seeds.'], conclusion: 'Flowers have different parts that help them grow and reproduce!' },
  { id: 'bio-9', title: 'Healthy Eating', icon: <Apple className="w-8 h-8" />, color: 'text-red-400', bgColor: 'bg-red-500/10', description: 'Foods that make you strong!', level: 2, steps: ['Fruits give vitamins.', 'Vegetables give fiber.', 'Protein builds muscle.', 'Water keeps you hydrated.'], conclusion: 'Eating a variety of healthy foods helps your body grow strong!' },
  { id: 'bio-10', title: 'My Skeleton', icon: <Bone className="w-8 h-8" />, color: 'text-gray-400', bgColor: 'bg-gray-500/10', description: 'The frame of your body!', level: 2, steps: ['Bones hold you up.', 'Your skull protects your brain.', 'Your ribs protect your heart.', 'Bones help you move.'], conclusion: 'Your skeleton gives your body shape and protects your organs!' },
  { id: 'bio-11', title: 'The Brain', icon: <Brain className="w-8 h-8" />, color: 'text-orange-400', bgColor: 'bg-orange-500/10', description: 'Your body’s computer!', level: 3, steps: ['The brain thinks.', 'It controls movement.', 'It stores memories.', 'It is always working.'], conclusion: 'Your brain controls everything your body does!' },
  { id: 'bio-12', title: 'The Lungs', icon: <Wind className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'How do you breathe?', level: 3, steps: ['You breathe in air.', 'Your lungs fill up.', 'Oxygen goes to blood.', 'You breathe out CO2.'], conclusion: 'Your lungs take in oxygen and remove carbon dioxide from your body!' },
  { id: 'bio-13', title: 'Food Chains', icon: <Magnet className="w-8 h-8" />, color: 'text-yellow-400', bgColor: 'bg-yellow-500/10', description: 'Who eats who?', level: 3, steps: ['The sun gives energy.', 'Plants make food.', 'Rabbits eat plants.', 'Foxes eat rabbits.'], conclusion: 'Energy moves through an ecosystem from the sun to plants to animals!' },
  { id: 'bio-14', title: 'The Ocean', icon: <Waves className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'Explore the deep blue sea!', level: 3, steps: ['Ocean covers most of Earth.', 'Fish live in the water.', 'Corals build reefs.', 'It is full of life!'], conclusion: 'The ocean is home to millions of plant and animal species!' },
  { id: 'bio-15', title: 'The Rainforest', icon: <TreePine className="w-8 h-8" />, color: 'text-green-400', bgColor: 'bg-green-500/10', description: 'The most diverse place on Earth!', level: 3, steps: ['It is warm and wet.', 'Many trees grow there.', 'Lots of animals live there.', 'It produces lots of oxygen.'], conclusion: 'Rainforests are essential for global biodiversity and climate!' },
  { id: 'bio-16', title: 'The Desert', icon: <Sun className="w-8 h-8" />, color: 'text-orange-400', bgColor: 'bg-orange-500/10', description: 'Where it is hot and dry!', level: 3, steps: ['It gets very little rain.', 'Cacti store water.', 'Camels survive heat.', 'Animals are nocturnal.'], conclusion: 'Desert plants and animals have special adaptations to survive the heat!' },
  { id: 'bio-17', title: 'The Arctic', icon: <Snowflake className="w-8 h-8" />, color: 'text-cyan-400', bgColor: 'bg-cyan-500/10', description: 'The frozen land!', level: 3, steps: ['It is freezing cold.', 'Ice covers the ground.', 'Polar bears live there.', 'Animals have thick fur.'], conclusion: 'Arctic animals are adapted to survive extreme cold!' },
  { id: 'bio-18', title: 'The Human Body', icon: <Heart className="w-8 h-8" />, color: 'text-red-400', bgColor: 'bg-red-500/10', description: 'A complex machine!', level: 4, steps: ['It has many systems.', 'The heart pumps blood.', 'The lungs breathe.', 'The brain thinks.'], conclusion: 'Your body is made of systems that work together to keep you alive!' },
  { id: 'bio-19', title: 'The Muscles', icon: <Activity className="w-8 h-8" />, color: 'text-rose-400', bgColor: 'bg-rose-500/10', description: 'How do you move?', level: 4, steps: ['Muscles pull bones.', 'They contract.', 'They relax.', 'They let you move.'], conclusion: 'Muscles work in pairs to help you move your body!' },
  { id: 'bio-20', title: 'The Digestive System', icon: <Droplets className="w-8 h-8" />, color: 'text-yellow-400', bgColor: 'bg-yellow-500/10', description: 'How your body uses food!', level: 4, steps: ['Food enters your mouth.', 'Your stomach breaks it down.', 'Your intestines absorb it.', 'Waste leaves the body.'], conclusion: 'Your digestive system breaks down food into nutrients your body can use!' },
  { id: 'bio-21', title: 'The Blood', icon: <Droplets className="w-8 h-8" />, color: 'text-red-400', bgColor: 'bg-red-500/10', description: 'Your body’s delivery system!', level: 4, steps: ['Blood carries oxygen.', 'It carries nutrients.', 'It fights infection.', 'It is red and liquid.'], conclusion: 'Blood transports essential materials throughout your body!' },
  { id: 'bio-22', title: 'The Immune System', icon: <Shield className="w-8 h-8" />, color: 'text-green-400', bgColor: 'bg-green-500/10', description: 'How you fight germs!', level: 4, steps: ['Germs enter your body.', 'White blood cells attack.', 'You get a fever.', 'You get better!'], conclusion: 'Your immune system protects you from harmful germs and viruses!' },
  { id: 'bio-23', title: 'The Nervous System', icon: <Brain className="w-8 h-8" />, color: 'text-purple-400', bgColor: 'bg-purple-500/10', description: 'Your body’s messenger!', level: 4, steps: ['Your brain sends signals.', 'Nerves carry them.', 'You feel and react.', 'It happens instantly!'], conclusion: 'Your nervous system sends messages between your brain and body!' },
  { id: 'bio-24', title: 'Endangered Species', icon: <Heart className="w-8 h-8" />, color: 'text-red-400', bgColor: 'bg-red-500/10', description: 'Animals that need our help!', level: 5, steps: ['Some animals are rare.', 'They lose their homes.', 'People hunt them.', 'We must protect them.'], conclusion: 'Conservation is crucial to protect endangered animals from extinction!' },
  { id: 'bio-25', title: 'Ecosystems', icon: <Leaf className="w-8 h-8" />, color: 'text-emerald-400', bgColor: 'bg-emerald-500/10', description: 'A community of life!', level: 5, steps: ['Living and non-living things.', 'They interact.', 'They share resources.', 'They form an ecosystem.'], conclusion: 'Ecosystems are balanced communities where living and non-living things interact!' },
  { id: 'bio-26', title: 'Photosynthesis', icon: <Sun className="w-8 h-8" />, color: 'text-yellow-400', bgColor: 'bg-yellow-500/10', description: 'How plants make food!', level: 5, steps: ['Plants absorb sunlight.', 'They drink water.', 'They take in CO2.', 'They make sugar!'], conclusion: 'Plants use sunlight, water, and carbon dioxide to make their own food!' },
  { id: 'bio-27', title: 'The Water Cycle', icon: <Waves className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'Nature’s recycling!', level: 5, steps: ['Sun heats water.', 'Water evaporates.', 'It forms clouds.', 'It rains back down!'], conclusion: 'Water constantly cycles through evaporation, condensation, and precipitation!' },
  { id: 'bio-28', title: 'Human Growth', icon: <Activity className="w-8 h-8" />, color: 'text-green-400', bgColor: 'bg-green-500/10', description: 'From baby to adult!', level: 5, steps: ['You were a baby.', 'You grew into a child.', 'Your bones grow.', 'You become an adult.'], conclusion: 'Your body grows and changes throughout your life as you age!' },
  { id: 'bio-29', title: 'Genetics Basics', icon: <Dna className="w-8 h-8" />, color: 'text-purple-400', bgColor: 'bg-purple-500/10', description: 'Why you look like your family!', level: 5, steps: ['You have genes.', 'Genes come from parents.', 'They make you unique.', 'They determine traits.'], conclusion: 'Genes are the instructions inside your cells that make you who you are!' },
  { id: 'bio-30', title: 'Microorganisms', icon: <Microscope className="w-8 h-8" />, color: 'text-teal-400', bgColor: 'bg-teal-500/10', description: 'Tiny living things!', level: 5, steps: ['Bacteria are tiny.', 'Some are good.', 'Some cause illness.', 'We use them for food.'], conclusion: 'Microorganisms are so small they can only be seen with a microscope!' },
  { id: 'bio-31', title: 'Animal Adaptations', icon: <Bug className="w-8 h-8" />, color: 'text-orange-400', bgColor: 'bg-orange-500/10', description: 'How animals survive!', level: 5, steps: ['Camels store water.', 'Chameleons change color.', 'Bears hibernate.', 'Animals adapt to survive.'], conclusion: 'Animals have unique adaptations to survive in their environments!' },
  { id: 'bio-32', title: 'Plant Adaptations', icon: <Sprout className="w-8 h-8" />, color: 'text-green-400', bgColor: 'bg-green-500/10', description: 'How plants survive!', level: 5, steps: ['Cacti store water.', 'Ferns love shade.', 'Some plants eat bugs.', 'Plants adapt to their home.'], conclusion: 'Plants have specialized structures to survive in their specific environments!' },
  { id: 'bio-33', title: 'Habitats', icon: <Home className="w-8 h-8" />, color: 'text-teal-400', bgColor: 'bg-teal-500/10', description: 'Where animals belong!', level: 5, steps: ['Animals have homes.', 'They are called habitats.', 'They need food and shelter.', 'They protect them.'], conclusion: 'Animals live in habitats that provide their basic needs!' },
  { id: 'bio-34', title: 'Food Webs', icon: <Magnet className="w-8 h-8" />, color: 'text-yellow-400', bgColor: 'bg-yellow-500/10', description: 'Complex connections!', level: 5, steps: ['Plants are producers.', 'Animals are consumers.', 'Fungi are decomposers.', 'All are connected.'], conclusion: 'A food web shows the interconnected feeding relationships in an ecosystem!' },
  { id: 'bio-35', title: 'The Bird', icon: <Bird className="w-8 h-8" />, color: 'text-sky-400', bgColor: 'bg-sky-500/10', description: 'A flying vertebrate!', level: 5, steps: ['Birds have feathers.', 'They lay eggs.', 'They have hollow bones.', 'They can fly.'], conclusion: 'Birds are warm-blooded vertebrates that have feathers and lay eggs!' },
  { id: 'bio-36', title: 'The Reptile', icon: <Bug className="w-8 h-8" />, color: 'text-green-400', bgColor: 'bg-green-500/10', description: 'Cold-blooded animals!', level: 5, steps: ['Reptiles are cold-blooded.', 'They have scales.', 'They lay eggs.', 'Snakes are reptiles.'], conclusion: 'Reptiles are cold-blooded vertebrates with dry, scaly skin!' },
  { id: 'bio-37', title: 'The Amphibian', icon: <Bug className="w-8 h-8" />, color: 'text-green-400', bgColor: 'bg-green-500/10', description: 'Lives in water and on land!', level: 5, steps: ['Frogs live in water.', 'They also live on land.', 'They have wet skin.', 'They are amphibians.'], conclusion: 'Amphibians spend part of their lives in water and part on land!' },
  { id: 'bio-38', title: 'The Fish', icon: <Fish className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'Living underwater!', level: 5, steps: ['Fish live in water.', 'They have gills.', 'They have fins.', 'Fish are vertebrates.'], conclusion: 'Fish are aquatic vertebrates that breathe through gills!' },
  { id: 'bio-39', title: 'The Mammal', icon: <Cat className="w-8 h-8" />, color: 'text-red-400', bgColor: 'bg-red-500/10', description: 'Warm-blooded animals!', level: 5, steps: ['Mammals have fur.', 'They drink milk.', 'They are warm-blooded.', 'Humans are mammals.'], conclusion: 'Mammals are warm-blooded animals that have hair and feed milk to their young!' },
  { id: 'bio-40', title: 'The Invertebrate', icon: <Bug className="w-8 h-8" />, color: 'text-teal-400', bgColor: 'bg-teal-500/10', description: 'Animals without backbones!', level: 5, steps: ['Invertebrates have no bones.', 'Insects are invertebrates.', 'Spiders too.', 'Jellyfish too.'], conclusion: 'Invertebrates are animals that do not have a backbone!' },
  { id: 'bio-41', title: 'The Vertebrate', icon: <Bone className="w-8 h-8" />, color: 'text-gray-400', bgColor: 'bg-gray-500/10', description: 'Animals with backbones!', level: 5, steps: ['Vertebrates have bones.', 'Fish are vertebrates.', 'Birds are vertebrates.', 'Mammals are too.'], conclusion: 'Vertebrates are animals that have a backbone or spinal column!' },
  { id: 'bio-42', title: 'The Natural World', icon: <Globe className="w-8 h-8" />, color: 'text-green-400', bgColor: 'bg-green-500/10', description: 'The wonder of nature!', level: 5, steps: ['Nature is beautiful.', 'It has many species.', 'It is balanced.', 'We must protect it.'], conclusion: 'The natural world is an amazing, interconnected system!' },
  { id: 'bio-43', title: 'Pollination', icon: <Flower2 className="w-8 h-8" />, color: 'text-pink-400', bgColor: 'bg-pink-500/10', description: 'How seeds are made!', level: 5, steps: ['Bees visit flowers.', 'They carry pollen.', 'Flowers make seeds.', 'New plants grow.'], conclusion: 'Pollination is essential for plants to reproduce and make seeds!' },
  { id: 'bio-44', title: 'Seed Dispersal', icon: <Wind className="w-8 h-8" />, color: 'text-green-400', bgColor: 'bg-green-500/10', description: 'How seeds travel!', level: 5, steps: ['Wind blows seeds.', 'Water carries seeds.', 'Animals drop seeds.', 'They grow far away.'], conclusion: 'Plants use various methods to spread their seeds to new locations!' },
  { id: 'bio-45', title: 'The Environment', icon: <Globe className="w-8 h-8" />, color: 'text-emerald-400', bgColor: 'bg-emerald-500/10', description: 'Protecting our home!', level: 5, steps: ['We need clean air.', 'We need clean water.', 'We protect animals.', 'We reduce waste.'], conclusion: 'Protecting the environment is vital for the health of all living things!' },
  { id: 'bio-46', title: 'Extinct Animals', icon: <Bone className="w-8 h-8" />, color: 'text-red-400', bgColor: 'bg-red-500/10', description: 'Gone forever!', level: 5, steps: ['Dinosaurs are extinct.', 'They lived long ago.', 'They disappeared.', 'We learn from fossils.'], conclusion: 'Extinction means a species has disappeared forever!' },
  { id: 'bio-47', title: 'Fossils', icon: <Bone className="w-8 h-8" />, color: 'text-orange-400', bgColor: 'bg-orange-500/10', description: 'Clues from the past!', level: 5, steps: ['Fossils are old bones.', 'They are in rocks.', 'They tell us the past.', 'Scientists study them.'], conclusion: 'Fossils are the preserved remains of ancient living things!' },
  { id: 'bio-48', title: 'Dinosaurs', icon: <Bone className="w-8 h-8" />, color: 'text-green-400', bgColor: 'bg-green-500/10', description: 'The giant reptiles!', level: 5, steps: ['Dinosaurs were huge.', 'They lived long ago.', 'Some ate plants.', 'Some ate meat.'], conclusion: 'Dinosaurs were a diverse group of reptiles that lived millions of years ago!' },
  { id: 'bio-49', title: 'The Human Heart', icon: <Heart className="w-8 h-8" />, color: 'text-red-400', bgColor: 'bg-red-500/10', description: 'The strongest muscle!', level: 5, steps: ['Your heart beats.', 'It pumps blood.', 'It beats 100,000 times a day.', 'It never stops.'], conclusion: 'Your heart is a powerful muscle that never stops pumping blood!' },
  { id: 'bio-50', title: 'Nature Walk', icon: <Leaf className="w-8 h-8" />, color: 'text-green-400', bgColor: 'bg-green-500/10', description: 'Discover your local nature!', level: 5, steps: ['Look at trees.', 'Look at insects.', 'Look at the sky.', 'Explore and learn!'], conclusion: 'Nature is everywhere, just waiting to be discovered!' },
];

// --- 50 PHYSICS EXPERIMENTS ---
const PHYSICS_EXPERIMENTS: Experiment[] = [
  { id: 'phy-1', title: 'Sink or Float?', icon: <Waves className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'Why do some objects sink and others float?', level: 1, steps: ['Place a rock in water.', 'It sinks.', 'Place a leaf in water.', 'It floats.'], conclusion: 'Objects denser than water sink; lighter ones float!' },
  { id: 'phy-2', title: 'Magnetic Force', icon: <Magnet className="w-8 h-8" />, color: 'text-purple-400', bgColor: 'bg-purple-500/10', description: 'What sticks to a magnet?', level: 1, steps: ['Bring a magnet to a paperclip.', 'It sticks!', 'Bring it to a wood block.', 'It does not stick.'], conclusion: 'Magnets attract objects made of iron, steel, nickel, or cobalt!' },
  { id: 'phy-3', title: 'Push and Pull', icon: <ArrowRight className="w-8 h-8" />, color: 'text-green-400', bgColor: 'bg-green-500/10', description: 'The forces that move things!', level: 1, steps: ['Push a box.', 'It moves away.', 'Pull a box.', 'It moves toward you.'], conclusion: 'A push moves things away, and a pull moves things closer!' },
  { id: 'phy-4', title: 'Gravity', icon: <ArrowDown className="w-8 h-8" />, color: 'text-red-400', bgColor: 'bg-red-500/10', description: 'What makes things fall down?', level: 1, steps: ['Drop a ball.', 'It falls.', 'It falls faster.', 'Gravity pulls it down.'], conclusion: 'Gravity pulls everything toward the center of the Earth!' },
  { id: 'phy-5', title: 'Light and Shadow', icon: <Sun className="w-8 h-8" />, color: 'text-yellow-400', bgColor: 'bg-yellow-500/10', description: 'How shadows are formed!', level: 1, steps: ['Light shines.', 'An object blocks it.', 'A shadow appears.', 'Move the light, the shadow moves.'], conclusion: 'Shadows are formed when an object blocks light!' },
  { id: 'phy-6', title: 'Sound Vibration', icon: <Activity className="w-8 h-8" />, color: 'text-purple-400', bgColor: 'bg-purple-500/10', description: 'How sound travels!', level: 1, steps: ['Pluck a guitar string.', 'It vibrates.', 'You hear a sound.', 'Sound needs a medium.'], conclusion: 'Sound travels through vibrations in air, water, and solids!' },
  { id: 'phy-7', title: 'Hot and Cold', icon: <Thermometer className="w-8 h-8" />, color: 'text-orange-400', bgColor: 'bg-orange-500/10', description: 'Learn about temperature!', level: 1, steps: ['Touch ice.', 'It feels cold.', 'Touch warm water.', 'It feels hot.'], conclusion: 'Temperature measures the average kinetic energy of particles!' },
  { id: 'phy-8', title: 'Friction', icon: <Activity className="w-8 h-8" />, color: 'text-gray-400', bgColor: 'bg-gray-500/10', description: 'What slows things down!', level: 1, steps: ['Rub your hands.', 'They get warm.', 'Friction creates heat.', 'It slows things down.'], conclusion: 'Friction is a force that opposes motion between two surfaces!' },
  { id: 'phy-9', title: 'Energy', icon: <Zap className="w-8 h-8" />, color: 'text-yellow-400', bgColor: 'bg-yellow-500/10', description: 'The power to do work!', level: 1, steps: ['Energy makes things move.', 'Light is energy.', 'Sound is energy.', 'Heat is energy.'], conclusion: 'Energy is the ability to do work!' },
  { id: 'phy-10', title: 'Ramps', icon: <Activity className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'How sloped surfaces help!', level: 1, steps: ['Put a ball on a ramp.', 'It rolls down.', 'Steeper ramps move faster.', 'Ramps make work easier.'], conclusion: 'Inclined planes or ramps make it easier to move objects up and down!' },
  { id: 'phy-11', title: 'Towers', icon: <Building2 className="w-8 h-8" />, color: 'text-gray-400', bgColor: 'bg-gray-500/10', description: 'What makes buildings strong?', level: 2, steps: ['Build with blocks.', 'Make a tall tower.', 'Test it.', 'Strong bases make tall towers.'], conclusion: 'A stable base and balance are essential for strong structures!' },
  { id: 'phy-12', title: 'Float and Sink', icon: <Waves className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'Density experiment!', level: 2, steps: ['Oil floats on water.', 'Water is denser.', 'A heavy rock sinks.', 'Density determines floating.'], conclusion: 'Objects float if they are less dense than the liquid they are placed in!' },
  { id: 'phy-13', title: 'Sound Pitch', icon: <Activity className="w-8 h-8" />, color: 'text-indigo-400', bgColor: 'bg-indigo-500/10', description: 'High or low?', level: 2, steps: ['Tap a small cup.', 'It makes a high sound.', 'Tap a big pot.', 'It makes a low sound.'], conclusion: 'The size of an object affects the pitch of the sound it makes!' },
  { id: 'phy-14', title: 'Magnetic Poles', icon: <Magnet className="w-8 h-8" />, color: 'text-purple-400', bgColor: 'bg-purple-500/10', description: 'North and South!', level: 2, steps: ['Bring two N poles together.', 'They push apart!', 'Bring N and S together.', 'They pull together!'], conclusion: 'Like magnetic poles repel each other, and opposite poles attract!' },
  { id: 'phy-15', title: 'Reflection', icon: <Activity className="w-8 h-8" />, color: 'text-cyan-400', bgColor: 'bg-cyan-500/10', description: 'How mirrors work!', level: 2, steps: ['Look in a mirror.', 'You see your reflection.', 'Light bounces off.', 'Mirrors are very smooth.'], conclusion: 'Mirrors reflect light and allow us to see our own image!' },
  { id: 'phy-16', title: 'Refraction', icon: <Droplets className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'Light bends!', level: 2, steps: ['Put a pencil in water.', 'It looks bent.', 'Light bends in water.', 'This is refraction.'], conclusion: 'Light changes direction when it passes from one transparent medium to another!' },
  { id: 'phy-17', title: 'Conductors', icon: <Zap className="w-8 h-8" />, color: 'text-yellow-400', bgColor: 'bg-yellow-500/10', description: 'Materials that carry electricity!', level: 2, steps: ['Metal is a conductor.', 'It lets electricity flow.', 'Plastic is an insulator.', 'It blocks electricity.'], conclusion: 'Conductors allow electricity to flow, while insulators block it!' },
  { id: 'phy-18', title: 'The Lever', icon: <Activity className="w-8 h-8" />, color: 'text-green-400', bgColor: 'bg-green-500/10', description: 'A simple machine!', level: 2, steps: ['A seesaw is a lever.', 'You push on one side.', 'The other side lifts.', 'Levers make work easier.'], conclusion: 'A lever is a simple machine that helps lift heavy objects with less force!' },
  { id: 'phy-19', title: 'The Pulley', icon: <Activity className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'A wheel and rope!', level: 2, steps: ['A pulley has a wheel.', 'The rope goes over it.', 'It helps lift heavy things.', 'It changes direction.'], conclusion: 'A pulley uses a wheel and rope to help lift objects more easily!' },
  { id: 'phy-20', title: 'Air', icon: <Wind className="w-8 h-8" />, color: 'text-gray-400', bgColor: 'bg-gray-500/10', description: 'The invisible force!', level: 2, steps: ['Air takes up space.', 'It fills a balloon.', 'It exerts pressure.', 'We need it to breathe.'], conclusion: 'Air is a mixture of gases that takes up space and exerts pressure!' },
  { id: 'phy-21', title: 'Water Pressure', icon: <Waves className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'The deeper you go, the more pressure!', level: 3, steps: ['Swim to the bottom.', 'Your ears feel pressure.', 'Water pushes on you.', 'Deeper water = more pressure.'], conclusion: 'Water pressure increases the deeper you go!' },
  { id: 'phy-22', title: 'The Wheel', icon: <Building2 className="w-8 h-8" />, color: 'text-orange-400', bgColor: 'bg-orange-500/10', description: 'A great invention!', level: 3, steps: ['Wheels roll.', 'They reduce friction.', 'Cars use them.', 'Bikes use them.'], conclusion: 'The wheel is one of the most important inventions in history!' },
  { id: 'phy-23', title: 'The Axle', icon: <Building2 className="w-8 h-8" />, color: 'text-gray-400', bgColor: 'bg-gray-500/10', description: 'The center of the wheel!', level: 3, steps: ['The axle is the center.', 'The wheel spins around it.', 'It helps things move.', 'It reduces friction.'], conclusion: 'An axle is the rod that passes through the center of a wheel!' },
  { id: 'phy-24', title: 'The Screw', icon: <Activity className="w-8 h-8" />, color: 'text-green-400', bgColor: 'bg-green-500/10', description: 'A spiral simple machine!', level: 3, steps: ['A screw has threads.', 'It grips materials.', 'It holds things together.', 'It is a simple machine.'], conclusion: 'A screw is a simple machine that converts rotational motion into linear motion!' },
  { id: 'phy-25', title: 'The Wedge', icon: <Activity className="w-8 h-8" />, color: 'text-orange-400', bgColor: 'bg-orange-500/10', description: 'A simple machine for splitting!', level: 3, steps: ['A knife is a wedge.', 'It is thin at the edge.', 'It splits things apart.', 'It is a simple machine.'], conclusion: 'A wedge is a simple machine that gets thinner at one end and is used to split or cut!' },
  { id: 'phy-26', title: 'Potential Energy', icon: <ArrowDown className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'Stored energy!', level: 3, steps: ['Lift a ball.', 'It has stored energy.', 'Drop it.', 'It moves.'], conclusion: 'Potential energy is stored energy that can be used later!' },
  { id: 'phy-27', title: 'Kinetic Energy', icon: <Zap className="w-8 h-8" />, color: 'text-yellow-400', bgColor: 'bg-yellow-500/10', description: 'Energy in motion!', level: 3, steps: ['Roll a ball.', 'It is moving.', 'It has kinetic energy.', 'The faster it moves, the more energy.'], conclusion: 'Kinetic energy is the energy an object has because it is moving!' },
  { id: 'phy-28', title: 'The Simple Circuit', icon: <Zap className="w-8 h-8" />, color: 'text-yellow-400', bgColor: 'bg-yellow-500/10', description: 'A path for electricity!', level: 3, steps: ['Connect a battery.', 'Connect a bulb.', 'Connect a wire.', 'The bulb lights up!'], conclusion: 'A circuit is a closed path that allows electricity to flow!' },
  { id: 'phy-29', title: 'Renewable Energy', icon: <Sun className="w-8 h-8" />, color: 'text-orange-400', bgColor: 'bg-orange-500/10', description: 'Clean energy for the future!', level: 3, steps: ['Solar energy comes from the sun.', 'Wind energy comes from wind.', 'Water energy comes from rivers.', 'They never run out.'], conclusion: 'Renewable energy comes from natural sources that are constantly replenished!' },
  { id: 'phy-30', title: 'The Rainbow', icon: <Rainbow className="w-8 h-8" />, color: 'text-indigo-400', bgColor: 'bg-indigo-500/10', description: 'Colors in the sky!', level: 3, steps: ['Light hits raindrops.', 'The drops bend the light.', 'The light splits.', 'You see a rainbow.'], conclusion: 'A rainbow forms when sunlight is refracted and reflected in water droplets!' },
  { id: 'phy-31', title: 'Wind Power', icon: <Wind className="w-8 h-8" />, color: 'text-cyan-400', bgColor: 'bg-cyan-500/10', description: 'Harnessing the wind!', level: 3, steps: ['Wind blows.', 'It hits a turbine.', 'The turbine spins.', 'It makes electricity.'], conclusion: 'Wind turbines capture the kinetic energy of the wind and convert it into electricity!' },
  { id: 'phy-32', title: 'Solar Power', icon: <Sun className="w-8 h-8" />, color: 'text-yellow-400', bgColor: 'bg-yellow-500/10', description: 'Power from the sun!', level: 3, steps: ['Sunlight hits a panel.', 'The panel absorbs it.', 'It makes electricity.', 'It powers homes.'], conclusion: 'Solar panels convert sunlight into electricity!' },
  { id: 'phy-33', title: 'Elasticity', icon: <Activity className="w-8 h-8" />, color: 'text-green-400', bgColor: 'bg-green-500/10', description: 'What stretches and snaps back!', level: 3, steps: ['Pull a rubber band.', 'It stretches.', 'Let go.', 'It snaps back!'], conclusion: 'Elastic materials stretch when pulled and return to their original shape!' },
  { id: 'phy-34', title: 'The Pendulum', icon: <Activity className="w-8 h-8" />, color: 'text-gray-400', bgColor: 'bg-gray-500/10', description: 'A swinging weight!', level: 3, steps: ['Attach a weight to a string.', 'Let it swing.', 'It swings back and forth.', 'It is a pendulum.'], conclusion: 'A pendulum is a weight that swings back and forth due to gravity!' },
  { id: 'phy-35', title: 'Newton’s First Law', icon: <Activity className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'Objects in motion stay in motion!', level: 4, steps: ['Roll a ball.', 'It keeps rolling.', 'Friction stops it.', 'It is Newton’s Law.'], conclusion: 'An object in motion stays in motion unless acted on by an outside force!' },
  { id: 'phy-36', title: 'Newton’s Second Law', icon: <Activity className="w-8 h-8" />, color: 'text-green-400', bgColor: 'bg-green-500/10', description: 'Force equals mass times acceleration!', level: 4, steps: ['Push a light ball.', 'It moves fast.', 'Push a heavy ball.', 'It moves slower.'], conclusion: 'The acceleration of an object depends on the force applied and its mass!' },
  { id: 'phy-37', title: 'Newton’s Third Law', icon: <Activity className="w-8 h-8" />, color: 'text-red-400', bgColor: 'bg-red-500/10', description: 'For every action, there is a reaction!', level: 4, steps: ['Jump off a boat.', 'The boat moves back.', 'You move forward.', 'It is action and reaction.'], conclusion: 'For every action, there is an equal and opposite reaction!' },
  { id: 'phy-38', title: 'Laws of Motion', icon: <Rocket className="w-8 h-8" />, color: 'text-orange-400', bgColor: 'bg-orange-500/10', description: 'The rules of movement!', level: 4, steps: ['Objects move.', 'They need force.', 'They stay in motion.', 'These are Newton’s laws.'], conclusion: 'Newton’s laws of motion describe how objects move and interact!' },
  { id: 'phy-39', title: 'The Atom', icon: <Atom className="w-8 h-8" />, color: 'text-purple-400', bgColor: 'bg-purple-500/10', description: 'The building block of everything!', level: 4, steps: ['Everything is made of atoms.', 'Atoms have a nucleus.', 'They have electrons.', 'They are very small.'], conclusion: 'Atoms are the basic building blocks of all matter!' },
  { id: 'phy-40', title: 'Electrons', icon: <Atom className="w-8 h-8" />, color: 'text-cyan-400', bgColor: 'bg-cyan-500/10', description: 'The tiny particles with charge!', level: 4, steps: ['Electrons orbit the nucleus.', 'They have a negative charge.', 'They help create electricity.', 'They are very tiny.'], conclusion: 'Electrons are negatively charged particles that orbit the nucleus of an atom!' },
  { id: 'phy-41', title: 'The Nucleus', icon: <Atom className="w-8 h-8" />, color: 'text-orange-400', bgColor: 'bg-orange-500/10', description: 'The center of the atom!', level: 4, steps: ['The nucleus is in the middle.', 'It has protons.', 'It has neutrons.', 'It is positively charged.'], conclusion: 'The nucleus contains protons and neutrons and makes up most of an atom’s mass!' },
  { id: 'phy-42', title: 'The Universe', icon: <Moon className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'Everything that exists!', level: 4, steps: ['The universe is huge.', 'It contains galaxies.', 'It contains stars.', 'It contains planets.'], conclusion: 'The universe contains everything, including all matter, energy, and space!' },
  { id: 'phy-43', title: 'The Earth', icon: <Globe className="w-8 h-8" />, color: 'text-green-400', bgColor: 'bg-green-500/10', description: 'Our beautiful home!', level: 4, steps: ['Earth is a planet.', 'It orbits the sun.', 'It has water.', 'It has life.'], conclusion: 'Earth is the only known planet to support life!' },
  { id: 'phy-44', title: 'The Moon', icon: <Moon className="w-8 h-8" />, color: 'text-gray-400', bgColor: 'bg-gray-500/10', description: 'Our closest neighbor!', level: 4, steps: ['The moon orbits Earth.', 'It reflects sunlight.', 'It affects tides.', 'It has no atmosphere.'], conclusion: 'The moon is Earth’s only natural satellite and affects ocean tides!' },
  { id: 'phy-45', title: 'The Sun', icon: <Sun className="w-8 h-8" />, color: 'text-yellow-400', bgColor: 'bg-yellow-500/10', description: 'Our source of light and heat!', level: 4, steps: ['The sun is a star.', 'It is very hot.', 'It gives light.', 'It gives heat.'], conclusion: 'The sun is a star that provides light and heat, making life possible on Earth!' },
  { id: 'phy-46', title: 'The Stars', icon: <Star className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'Distant suns!', level: 4, steps: ['Stars are like our sun.', 'They are far away.', 'They look tiny.', 'They are huge.'], conclusion: 'Stars are giant balls of hot gas that emit light!' },
  { id: 'phy-47', title: 'The Planets', icon: <Activity className="w-8 h-8" />, color: 'text-purple-400', bgColor: 'bg-purple-500/10', description: 'The solar system!', level: 4, steps: ['Mercury is close.', 'Mars is the red planet.', 'Jupiter is the biggest.', 'There are 8 planets.'], conclusion: 'Our solar system has eight planets orbiting the sun!' },
  { id: 'phy-48', title: 'Solar System', icon: <Moon className="w-8 h-8" />, color: 'text-indigo-400', bgColor: 'bg-indigo-500/10', description: 'Our cosmic neighborhood!', level: 4, steps: ['The sun is the center.', 'Planets orbit it.', 'Asteroids also orbit.', 'It is huge.'], conclusion: 'Our solar system contains the sun, planets, moons, and other celestial bodies!' },
  { id: 'phy-49', title: 'Space Exploration', icon: <Rocket className="w-8 h-8" />, color: 'text-orange-400', bgColor: 'bg-orange-500/10', description: 'Traveling to the stars!', level: 4, steps: ['Rockets fly to space.', 'Astronauts explore.', 'They collect data.', 'They bring it home.'], conclusion: 'Humans have explored space using rockets and technology!' },
  { id: 'phy-50', title: 'The Sky', icon: <Cloud className="w-8 h-8" />, color: 'text-sky-400', bgColor: 'bg-sky-500/10', description: 'The world above us!', level: 4, steps: ['The sky is blue.', 'Clouds float in it.', 'Birds fly in it.', 'It is full of wonder.'], conclusion: 'The sky is a vast, dynamic part of our planet!' },
];

// --- 50 CHEMISTRY EXPERIMENTS ---
const CHEMISTRY_EXPERIMENTS: Experiment[] = [
  { id: 'chem-1', title: 'Mixing Colors', icon: <FlaskConical className="w-8 h-8" />, color: 'text-pink-400', bgColor: 'bg-pink-500/10', description: 'What happens when you mix red and blue?', level: 1, steps: ['You have red paint.', 'You have blue paint.', 'Mix them together.', 'You get purple!'], conclusion: 'Mixing primary colors creates secondary colors!' },
  { id: 'chem-2', title: 'States of Matter', icon: <Droplets className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'Solid, liquid, and gas!', level: 1, steps: ['Water is a liquid.', 'Ice is a solid.', 'Steam is a gas.', 'All are water.'], conclusion: 'Matter exists in three main states: solid, liquid, and gas!' },
  { id: 'chem-3', title: 'Fizzing Volcano', icon: <Flame className="w-8 h-8" />, color: 'text-orange-400', bgColor: 'bg-orange-500/10', description: 'A bubbly chemical reaction!', level: 1, steps: ['Put baking soda in a cup.', 'Add vinegar.', 'It fizzes!', 'It bubbles over.'], conclusion: 'Mixing baking soda and vinegar causes a chemical reaction that produces carbon dioxide gas!' },
  { id: 'chem-4', title: 'Sink or Dissolve', icon: <FlaskConical className="w-8 h-8" />, color: 'text-purple-400', bgColor: 'bg-purple-500/10', description: 'What happens in water?', level: 1, steps: ['Put salt in water.', 'It dissolves.', 'Put sand in water.', 'It does not dissolve.'], conclusion: 'Some substances dissolve in water (soluble), while others do not (insoluble)!' },
  { id: 'chem-5', title: 'Color Change', icon: <TestTube2 className="w-8 h-8" />, color: 'text-red-400', bgColor: 'bg-red-500/10', description: 'Acids and bases!', level: 1, steps: ['Use red cabbage juice.', 'Add lemon juice.', 'It turns red.', 'It is an acid.'], conclusion: 'Natural indicators change color in the presence of acids and bases!' },
  { id: 'chem-6', title: 'Melting and Freezing', icon: <Thermometer className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'Changing states!', level: 1, steps: ['Heat ice.', 'It melts.', 'Freeze water.', 'It turns to ice.'], conclusion: 'Adding or removing heat changes matter from one state to another!' },
  { id: 'chem-7', title: 'Gas Bubbles', icon: <Droplets className="w-8 h-8" />, color: 'text-cyan-400', bgColor: 'bg-cyan-500/10', description: 'Bubbles are gas!', level: 1, steps: ['Mix a fizzy tablet.', 'It creates gas.', 'Gas makes bubbles.', 'Bubbles rise.'], conclusion: 'Chemical reactions can produce gas, which creates bubbles!' },
  { id: 'chem-8', title: 'Evaporation', icon: <Sun className="w-8 h-8" />, color: 'text-yellow-400', bgColor: 'bg-yellow-500/10', description: 'Water disappears!', level: 1, steps: ['Put water out.', 'Leave it in the sun.', 'It disappears.', 'It evaporates.'], conclusion: 'Evaporation is when a liquid changes into a gas due to heat!' },
  { id: 'chem-9', title: 'Condensation', icon: <Waves className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'Gas becomes liquid!', level: 1, steps: ['Warm air hits a cold glass.', 'Water droplets form.', 'Gas turns to liquid.', 'This is condensation.'], conclusion: 'Condensation is when a gas changes into a liquid!' },
  { id: 'chem-10', title: 'Water Molecules', icon: <Droplets className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'What is water made of?', level: 1, steps: ['Water is H2O.', 'It has two hydrogens.', 'It has one oxygen.', 'They are tiny molecules.'], conclusion: 'Water is made of hydrogen and oxygen molecules!' },
  { id: 'chem-11', title: 'Melting Chocolate', icon: <Thermometer className="w-8 h-8" />, color: 'text-orange-400', bgColor: 'bg-orange-500/10', description: 'Solid to liquid!', level: 1, steps: ['Chocolate is solid.', 'Heat it.', 'It melts.', 'It becomes liquid.'], conclusion: 'Heat causes chocolate to change from a solid to a liquid!' },
  { id: 'chem-12', title: 'Freezing Water', icon: <Snowflake className="w-8 h-8" />, color: 'text-cyan-400', bgColor: 'bg-cyan-500/10', description: 'Liquid to solid!', level: 1, steps: ['Water is liquid.', 'Freeze it.', 'It becomes ice.', 'Ice is solid.'], conclusion: 'Cold temperatures cause liquid water to freeze into solid ice!' },
  { id: 'chem-13', title: 'Properties of Materials', icon: <FlaskConical className="w-8 h-8" />, color: 'text-gray-400', bgColor: 'bg-gray-500/10', description: 'Different materials have different properties!', level: 1, steps: ['Wood is hard.', 'Cotton is soft.', 'Glass is clear.', 'Metal is shiny.'], conclusion: 'Materials have different properties, such as hardness, softness, and shine!' },
  { id: 'chem-14', title: 'Mixing Liquids', icon: <FlaskConical className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'What mixes and what doesn’t?', level: 1, steps: ['Water and juice mix.', 'They blend together.', 'Oil and water do not mix.', 'Oil floats on top.'], conclusion: 'Liquids have different densities, which determines whether they mix or separate!' },
  { id: 'chem-15', title: 'Erupting Fizz', icon: <FlaskConical className="w-8 h-8" />, color: 'text-green-400', bgColor: 'bg-green-500/10', description: 'A mini explosion!', level: 1, steps: ['Put vinegar in a bottle.', 'Add baking soda.', 'It fizzes.', 'It erupts!'], conclusion: 'The reaction between vinegar and baking soda produces carbon dioxide gas, causing an eruption!' },
  { id: 'chem-16', title: 'Reactions', icon: <FlaskConical className="w-8 h-8" />, color: 'text-purple-400', bgColor: 'bg-purple-500/10', description: 'When substances change!', level: 1, steps: ['Mix two things.', 'They change.', 'Something new forms.', 'This is a reaction.'], conclusion: 'A chemical reaction produces new substances!' },
  { id: 'chem-17', title: 'Freezing Point', icon: <Thermometer className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'The temperature of freezing!', level: 1, steps: ['Water freezes at 0°C.', 'It becomes ice.', 'Below 0°C is colder.', 'It stays solid.'], conclusion: 'Water freezes into ice at 0 degrees Celsius!' },
  { id: 'chem-18', title: 'Boiling Point', icon: <Flame className="w-8 h-8" />, color: 'text-orange-400', bgColor: 'bg-orange-500/10', description: 'The temperature of boiling!', level: 1, steps: ['Water boils at 100°C.', 'It becomes steam.', 'Steam is very hot.', 'It is a gas.'], conclusion: 'Water boils into steam at 100 degrees Celsius!' },
  { id: 'chem-19', title: 'Atoms', icon: <Atom className="w-8 h-8" />, color: 'text-purple-400', bgColor: 'bg-purple-500/10', description: 'The tiny building blocks of matter!', level: 1, steps: ['Everything is made of atoms.', 'They are very small.', 'They combine into molecules.', 'They make everything.'], conclusion: 'All matter is made of tiny particles called atoms!' },
  { id: 'chem-20', title: 'Elements', icon: <FlaskConical className="w-8 h-8" />, color: 'text-yellow-400', bgColor: 'bg-yellow-500/10', description: 'Pure substances!', level: 1, steps: ['Elements are pure.', 'Oxygen is an element.', 'Gold is an element.', 'Carbon is an element.'], conclusion: 'Elements are the basic building blocks of matter, made of only one type of atom!' },
  { id: 'chem-21', title: 'Mixtures', icon: <FlaskConical className="w-8 h-8" />, color: 'text-teal-400', bgColor: 'bg-teal-500/10', description: 'Combining substances!', level: 1, steps: ['Mix salt and sand.', 'It is a mixture.', 'You can separate them.', 'Mixtures combine two things.'], conclusion: 'Mixtures are combinations of substances that can be physically separated!' },
  { id: 'chem-22', title: 'Density', icon: <Waves className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'How heavy something is!', level: 1, steps: ['A rock is dense.', 'A sponge is not.', 'Density is how heavy.', 'It determines sinking.'], conclusion: 'Density is the amount of mass in a given volume!' },
  { id: 'chem-23', title: 'Filtration', icon: <TestTube2 className="w-8 h-8" />, color: 'text-gray-400', bgColor: 'bg-gray-500/10', description: 'Separating mixtures!', level: 1, steps: ['Mix sand and water.', 'Use a filter.', 'Sand stays behind.', 'Water passes through.'], conclusion: 'Filtration is a method for separating solids from liquids!' },
  { id: 'chem-24', title: 'Chemical Change', icon: <TestTube2 className="w-8 h-8" />, color: 'text-orange-400', bgColor: 'bg-orange-500/10', description: 'When things transform!', level: 1, steps: ['Burn paper.', 'It turns to ash.', 'It is a chemical change.', 'It cannot be undone.'], conclusion: 'Chemical changes produce new substances that cannot be easily reversed!' },
  { id: 'chem-25', title: 'Physical Change', icon: <Building2 className="w-8 h-8" />, color: 'text-green-400', bgColor: 'bg-green-500/10', description: 'When things change shape!', level: 1, steps: ['Cut paper.', 'It is smaller.', 'It is a physical change.', 'It is still paper.'], conclusion: 'Physical changes alter the form of a substance but not its chemical composition!' },
  { id: 'chem-26', title: 'Salt', icon: <Sparkles className="w-8 h-8" />, color: 'text-white-400', bgColor: 'bg-white-500/10', description: 'The tasty mineral!', level: 1, steps: ['Salt is a mineral.', 'It is in the sea.', 'It is in rocks.', 'It makes food tasty.'], conclusion: 'Salt is a mineral made of sodium and chlorine!' },
  { id: 'chem-27', title: 'Sugar', icon: <Sparkles className="w-8 h-8" />, color: 'text-white-400', bgColor: 'bg-white-500/10', description: 'The sweet substance!', level: 1, steps: ['Sugar is sweet.', 'It dissolves in water.', 'It comes from plants.', 'It is a carbohydrate.'], conclusion: 'Sugar is a carbohydrate that provides energy for the body!' },
  { id: 'chem-28', title: 'Carbon Dioxide', icon: <Wind className="w-8 h-8" />, color: 'text-gray-400', bgColor: 'bg-gray-500/10', description: 'What we breathe out!', level: 1, steps: ['We breathe out CO2.', 'Plants breathe it in.', 'It is a gas.', 'It is invisible.'], conclusion: 'Carbon dioxide is a gas that plants use for photosynthesis!' },
  { id: 'chem-29', title: 'Oxygen', icon: <Wind className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'What we breathe in!', level: 1, steps: ['We breathe in oxygen.', 'Plants make it.', 'It is a gas.', 'We need it to live.'], conclusion: 'Oxygen is a gas essential for life on Earth!' },
  { id: 'chem-30', title: 'Hydrogen', icon: <FlaskConical className="w-8 h-8" />, color: 'text-cyan-400', bgColor: 'bg-cyan-500/10', description: 'The lightest element!', level: 1, steps: ['Hydrogen is a gas.', 'It is very light.', 'It is in water.', 'It is the lightest.'], conclusion: 'Hydrogen is the lightest and most abundant element in the universe!' },
  { id: 'chem-31', title: 'Mixing Acid & Base', icon: <TestTube2 className="w-8 h-8" />, color: 'text-green-400', bgColor: 'bg-green-500/10', description: 'A chemical reaction!', level: 4, steps: ['Acids and bases react.', 'They neutralize.', 'They make salt and water.', 'It is a reaction.'], conclusion: 'Acids and bases react to neutralize each other, producing salt and water!' },
  { id: 'chem-32', title: 'Ions', icon: <Atom className="w-8 h-8" />, color: 'text-purple-400', bgColor: 'bg-purple-500/10', description: 'Charged atoms!', level: 4, steps: ['Atoms can lose electrons.', 'They become positive.', 'They can gain electrons.', 'They become negative.'], conclusion: 'Ions are atoms that have a positive or negative charge!' },
  { id: 'chem-33', title: 'Acid', icon: <TestTube2 className="w-8 h-8" />, color: 'text-red-400', bgColor: 'bg-red-500/10', description: 'Sour and reactive!', level: 4, steps: ['Lemon juice is an acid.', 'Vinegar is an acid.', 'They are sour.', 'They react with metals.'], conclusion: 'Acids are substances that taste sour and can react with metals!' },
  { id: 'chem-34', title: 'Base', icon: <TestTube2 className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'Bitter and slippery!', level: 4, steps: ['Soap is a base.', 'Baking soda is a base.', 'They feel slippery.', 'They are bitter.'], conclusion: 'Bases are substances that taste bitter and feel slippery!' },
  { id: 'chem-35', title: 'pH Scale', icon: <TestTube2 className="w-8 h-8" />, color: 'text-green-400', bgColor: 'bg-green-500/10', description: 'How acidic or basic!', level: 4, steps: ['pH goes from 0 to 14.', '0 is strong acid.', '7 is neutral.', '14 is strong base.'], conclusion: 'The pH scale measures how acidic or basic a substance is!' },
  { id: 'chem-36', title: 'Neutralization', icon: <TestTube2 className="w-8 h-8" />, color: 'text-orange-400', bgColor: 'bg-orange-500/10', description: 'When acid meets base!', level: 4, steps: ['Acid and base mix.', 'They cancel each other.', 'They become neutral.', 'The reaction is called neutralization.'], conclusion: 'Neutralization is the reaction between an acid and a base!' },
  { id: 'chem-37', title: 'Baking Soda', icon: <TestTube2 className="w-8 h-8" />, color: 'text-pink-400', bgColor: 'bg-pink-500/10', description: 'A versatile chemical!', level: 4, steps: ['Baking soda is a base.', 'It reacts with acids.', 'It makes things fluffy.', 'It is used in baking.'], conclusion: 'Baking soda is a chemical compound used in cooking and cleaning!' },
  { id: 'chem-38', title: 'Vinegar', icon: <TestTube2 className="w-8 h-8" />, color: 'text-brown-400', bgColor: 'bg-brown-500/10', description: 'A sour acid!', level: 4, steps: ['Vinegar is an acid.', 'It is made from fruits.', 'It is sour.', 'It is used in cooking.'], conclusion: 'Vinegar is a liquid made from fermented fruit or grain!' },
  { id: 'chem-39', title: 'H2O', icon: <Droplets className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'The chemical formula for water!', level: 4, steps: ['Water is H2O.', 'H is hydrogen.', 'O is oxygen.', 'It is essential for life.'], conclusion: 'Water is a molecule made of two hydrogen atoms and one oxygen atom!' },
  { id: 'chem-40', title: 'The Periodic Table', icon: <FlaskConical className="w-8 h-8" />, color: 'text-gray-400', bgColor: 'bg-gray-500/10', description: 'A map of elements!', level: 4, steps: ['It lists all elements.', 'It groups them by type.', 'Scientists use it.', 'It is a valuable tool.'], conclusion: 'The periodic table organizes all known chemical elements!' },
  { id: 'chem-41', title: 'Crystals', icon: <Droplets className="w-8 h-8" />, color: 'text-cyan-400', bgColor: 'bg-cyan-500/10', description: 'Beautiful solid shapes!', level: 4, steps: ['Crystals are solids.', 'They have a pattern.', 'They are formed slowly.', 'Salt and sugar are crystals.'], conclusion: 'Crystals are solids with a highly ordered, repeating atomic structure!' },
  { id: 'chem-42', title: 'Chemical Bond', icon: <Atom className="w-8 h-8" />, color: 'text-purple-400', bgColor: 'bg-purple-500/10', description: 'How atoms stick together!', level: 4, steps: ['Atoms stick together.', 'They form bonds.', 'Bonds create molecules.', 'They are strong.'], conclusion: 'Chemical bonds hold atoms together to form molecules!' },
  { id: 'chem-43', title: 'Protons', icon: <Atom className="w-8 h-8" />, color: 'text-red-400', bgColor: 'bg-red-500/10', description: 'Positively charged particles!', level: 4, steps: ['Protons are in the nucleus.', 'They are positive.', 'They determine the element.', 'They are tiny.'], conclusion: 'Protons are positively charged particles found in the nucleus of an atom!' },
  { id: 'chem-44', title: 'Neutrons', icon: <Atom className="w-8 h-8" />, color: 'text-gray-400', bgColor: 'bg-gray-500/10', description: 'No charge at all!', level: 4, steps: ['Neutrons are in the nucleus.', 'They have no charge.', 'They add mass.', 'They are neutral.'], conclusion: 'Neutrons are neutrally charged particles found in the nucleus of an atom!' },
  { id: 'chem-45', title: 'The Air', icon: <Wind className="w-8 h-8" />, color: 'text-blue-400', bgColor: 'bg-blue-500/10', description: 'A mixture of gases!', level: 4, steps: ['Air is a mixture.', 'It contains oxygen.', 'It contains nitrogen.', 'It contains CO2.'], conclusion: 'Air is a mixture of gases, primarily nitrogen, oxygen, and carbon dioxide!' },
  { id: 'chem-46', title: 'Burn', icon: <Flame className="w-8 h-8" />, color: 'text-orange-400', bgColor: 'bg-orange-500/10', description: 'A chemical reaction!', level: 4, steps: ['Fire burns things.', 'It uses oxygen.', 'It produces heat.', 'It is a chemical reaction.'], conclusion: 'Burning is a chemical reaction that produces heat and light!' },
  { id: 'chem-47', title: 'Rust', icon: <FlaskConical className="w-8 h-8" />, color: 'text-orange-400', bgColor: 'bg-orange-500/10', description: 'When metal reacts!', level: 4, steps: ['Iron reacts with oxygen.', 'It forms rust.', 'Rust is a new substance.', 'It is a chemical change.'], conclusion: 'Rusting is a chemical reaction between iron and oxygen!' },
  { id: 'chem-48', title: 'Decomposition', icon: <FlaskConical className="w-8 h-8" />, color: 'text-brown-400', bgColor: 'bg-brown-500/10', description: 'Things breaking down!', level: 4, steps: ['Leaves rot.', 'They decompose.', 'They turn into soil.', 'It is a chemical change.'], conclusion: 'Decomposition is the chemical breakdown of organic matter!' },
  { id: 'chem-49', title: 'Combustion', icon: <Flame className="w-8 h-8" />, color: 'text-red-400', bgColor: 'bg-red-500/10', description: 'Burning with oxygen!', level: 4, steps: ['Fuel burns with oxygen.', 'It makes fire.', 'It gives heat.', 'It is combustion.'], conclusion: 'Combustion is a rapid chemical reaction between a fuel and oxygen that produces heat!' },
  { id: 'chem-50', title: 'Chemistry in Nature', icon: <Leaf className="w-8 h-8" />, color: 'text-green-400', bgColor: 'bg-green-500/10', description: 'The chemistry of the world!', level: 4, steps: ['Nature is full of chemistry.', 'Photosynthesis is chemistry.', 'Digestion is chemistry.', 'Chemistry is everywhere!'], conclusion: 'Chemistry is everywhere in nature, from the air we breathe to the food we eat!' },
];

// --- Component ---
interface ScienceLabProps {
  type: 'biology' | 'physics' | 'chemistry';
}

export const ScienceLab: React.FC<ScienceLabProps> = ({ type }) => {
  const [selectedExperiment, setSelectedExperiment] = useState<Experiment | null>(null);

  const experiments = type === 'biology' ? BIOLOGY_EXPERIMENTS : type === 'physics' ? PHYSICS_EXPERIMENTS : CHEMISTRY_EXPERIMENTS;
  const title = type === 'biology' ? '🔬 Biology Lab' : type === 'physics' ? '⚛️ Physics Lab' : '🧪 Chemistry Lab';

  // --- EXPERIMENT PLAYER (Inside the same component) ---
  if (selectedExperiment) {
    const [step, setStep] = useState(0);
    return (
      <div className="max-w-2xl w-full mx-auto bg-app-card/80 backdrop-blur-md border border-white/5 rounded-3xl shadow-[0_20px_50px_rgba(0,0,0,0.8)] p-6 relative overflow-hidden text-center">
        <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 opacity-50" />
        
        <h2 className="text-2xl font-bold text-white mb-4">{selectedExperiment.title}</h2>
        <p className="text-gray-400 mb-4">{selectedExperiment.description}</p>

        <div className="bg-[#1a1a1a] p-6 rounded-xl border border-gray-800 min-h-[200px] flex flex-col justify-center mb-6">
          <div className="text-4xl mb-3">{selectedExperiment.icon}</div>
          <p className="text-lg text-white font-bold">{selectedExperiment.steps[step]}</p>
          <p className="text-xs text-gray-500 mt-2">Step {step + 1} of {selectedExperiment.steps.length}</p>
        </div>

        <div className="flex justify-between gap-4">
          <button onClick={() => setStep(Math.max(0, step - 1))} disabled={step === 0} className="px-4 py-2 bg-gray-800 rounded-lg text-white font-bold hover:bg-gray-700 disabled:opacity-30">← Back</button>
          {step < selectedExperiment.steps.length - 1 ? (
            <button onClick={() => setStep(step + 1)} className="px-4 py-2 bg-indigo-600 rounded-lg text-white font-bold hover:bg-indigo-500">Next Step →</button>
          ) : (
            <button onClick={() => setSelectedExperiment(null)} className="px-4 py-2 bg-green-600 rounded-lg text-white font-bold hover:bg-green-500">✔ Done!</button>
          )}
        </div>

        {step === selectedExperiment.steps.length - 1 && (
          <div className="mt-6 p-4 bg-green-500/20 border border-green-500/50 rounded-xl text-green-400 font-bold">
            🧪 {selectedExperiment.conclusion}
          </div>
        )}
      </div>
    );
  }

  // --- EXPERIMENT LIST ---
  return (
    <div className="max-w-2xl w-full mx-auto bg-app-card/80 backdrop-blur-md border border-white/5 rounded-3xl shadow-[0_20px_50px_rgba(0,0,0,0.8)] p-6 relative overflow-hidden">
      <div className={`absolute inset-0 ${type === 'biology' ? 'bg-emerald-500/5' : type === 'physics' ? 'bg-blue-500/5' : 'bg-purple-500/5'} blur-[100px] -z-10`} />
      <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 opacity-50" />

      <div className="flex justify-between items-center mb-6 border-b border-white/10 pb-4">
        <h2 className="text-2xl font-bold text-white flex items-center gap-3">
          {title}
        </h2>
        <div className="text-xs text-gray-400 bg-white/5 px-3 py-1 rounded-full border border-white/5">
          {experiments.length} Experiments
        </div>
      </div>

      <p className="text-gray-400 text-sm mb-6">Choose an experiment to begin your discovery!</p>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {experiments.map((exp) => (
          <motion.button
            key={exp.id}
            whileHover={{ scale: 1.03, y: -3 }}
            whileTap={{ scale: 0.98 }}
            onClick={() => setSelectedExperiment(exp)}
            className={`${exp.bgColor} border border-white/10 hover:border-white/30 p-5 rounded-xl text-left transition-all relative overflow-hidden group`}
          >
            <div className={`absolute inset-0 ${exp.color} opacity-0 group-hover:opacity-10 blur-xl transition-opacity duration-500`} />
            
            <div className={`${exp.color} mb-3 flex justify-between items-center`}>
              {exp.icon}
              <span className="text-[10px] bg-gray-800 px-2 py-0.5 rounded-full text-gray-400">Level {exp.level}</span>
            </div>
            <h4 className="text-white font-bold text-lg">{exp.title}</h4>
            <p className="text-gray-400 text-sm line-clamp-2 mt-1">{exp.description}</p>
          </motion.button>
        ))}
      </div>
    </div>
  );
};

// Export for use in VirtualLab.tsx (if needed)
export { BIOLOGY_EXPERIMENTS, PHYSICS_EXPERIMENTS, CHEMISTRY_EXPERIMENTS };