import { Lesson } from '../types';

export const SCIENCE_CURRICULUM: Lesson[] = [
  // --- FOUNDATION (Level 1): Sensorial Exploration ---
  { id: 'sci-f1-senses', framework: 'cambridge-primary', ageGroup: '4-5', subject: 'science', title: 'My Five Senses', description: 'Discover how we see, hear, smell, taste, and touch', skill: 'Observation', tags: ['Foundation'], prerequisites: [], difficulty: 'sensorial', montessoriArea: 'Cultural', cambridgeStrand: 'Science', activities: [{ id: 'act-sci-f1', type: 'explore', instructions: ['Learn your senses'], successCriteria: ['Identifies senses'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-f1', type: 'score', masteryScore: 80 } },
  { id: 'sci-f2-living', framework: 'cambridge-primary', ageGroup: '4-5', subject: 'science', title: 'Living vs Non-Living', description: 'What is alive and what is not?', skill: 'Classification', tags: ['Foundation'], prerequisites: ['sci-f1-senses'], difficulty: 'sensorial', montessoriArea: 'Cultural', cambridgeStrand: 'Science', activities: [{ id: 'act-sci-f2', type: 'match', instructions: ['Sort living things'], successCriteria: ['Correct sorting'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-f2', type: 'score', masteryScore: 80 } },
  { id: 'sci-f3-sinkfloat', framework: 'cambridge-primary', ageGroup: '4-5', subject: 'science', title: 'Sink or Float?', description: 'Test which objects sink in water', skill: 'Buoyancy', tags: ['Foundation'], prerequisites: [], difficulty: 'sensorial', montessoriArea: 'Cultural', cambridgeStrand: 'Science', activities: [{ id: 'act-sci-f3', type: 'experiment', instructions: ['Test buoyancy'], successCriteria: ['Predicts correctly'], componentId: 'PhysicsLab' }], assessment: { id: 'assess-sci-f3', type: 'score', masteryScore: 80 } },

  // --- LEVEL 1: Biology & Plants ---
  { id: 'sci-l1-plantparts', framework: 'cambridge-primary', ageGroup: '5-6', subject: 'science', title: 'Parts of a Plant', description: 'Roots, stems, leaves, and flowers', skill: 'Botany', tags: ['Level 1'], prerequisites: ['sci-f2-living'], difficulty: 'concrete', montessoriArea: 'Cultural', cambridgeStrand: 'Biology', activities: [{ id: 'act-sci-l1', type: 'identify', instructions: ['Identify plant parts'], successCriteria: ['Names parts'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-l1', type: 'score', masteryScore: 80 } },
  { id: 'sci-l2-seed', framework: 'cambridge-primary', ageGroup: '5-6', subject: 'science', title: 'From Seed to Plant', description: 'Watch a seed grow into a flower', skill: 'Life Cycles', tags: ['Level 1'], prerequisites: ['sci-l1-plantparts'], difficulty: 'concrete', montessoriArea: 'Cultural', cambridgeStrand: 'Biology', activities: [{ id: 'act-sci-l2', type: 'sequence', instructions: ['Arrange life cycle'], successCriteria: ['Correct order'], componentId: 'VirtualLab' }], assessment: { id: 'assess-sci-l2', type: 'score', masteryScore: 80 } },
  { id: 'sci-l3-animals', framework: 'cambridge-primary', ageGroup: '5-6', subject: 'science', title: 'Animal Habitats', description: 'Where do animals live?', skill: 'Ecology', tags: ['Level 1'], prerequisites: [], difficulty: 'concrete', montessoriArea: 'Cultural', cambridgeStrand: 'Biology', activities: [{ id: 'act-sci-l3', type: 'match', instructions: ['Match animal to home'], successCriteria: ['Correct matches'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-l3', type: 'score', masteryScore: 80 } },
  { id: 'sci-l4-frog', framework: 'cambridge-primary', ageGroup: '5-6', subject: 'science', title: 'Frog Life Cycle', description: 'From egg to tadpole to frog', skill: 'Metamorphosis', tags: ['Level 1'], prerequisites: ['sci-l2-seed'], difficulty: 'concrete', montessoriArea: 'Cultural', cambridgeStrand: 'Biology', activities: [{ id: 'act-sci-l4', type: 'sequence', instructions: ['Arrange frog cycle'], successCriteria: ['Correct order'], componentId: 'VirtualLab' }], assessment: { id: 'assess-sci-l4', type: 'score', masteryScore: 80 } },

  // --- LEVEL 2: Physics & Forces ---
  { id: 'sci-l5-magnets', framework: 'cambridge-primary', ageGroup: '6-7', subject: 'science', title: 'Magnetic Force', description: 'What sticks to a magnet?', skill: 'Magnetism', tags: ['Level 2'], prerequisites: [], difficulty: 'concrete', montessoriArea: 'Cultural', cambridgeStrand: 'Physics', activities: [{ id: 'act-sci-l5', type: 'experiment', instructions: ['Test magnetic objects'], successCriteria: ['Identifies magnets'], componentId: 'PhysicsLab' }], assessment: { id: 'assess-sci-l5', type: 'score', masteryScore: 80 } },
  { id: 'sci-l6-pushpull', framework: 'cambridge-primary', ageGroup: '6-7', subject: 'science', title: 'Push and Pull', description: 'Learn about forces', skill: 'Forces', tags: ['Level 2'], prerequisites: [], difficulty: 'abstract', montessoriArea: 'Cultural', cambridgeStrand: 'Physics', activities: [{ id: 'act-sci-l6', type: 'identify', instructions: ['Identify forces'], successCriteria: ['Correct identification'], componentId: 'PhysicsLab' }], assessment: { id: 'assess-sci-l6', type: 'score', masteryScore: 80 } },
  { id: 'sci-l7-light', framework: 'cambridge-primary', ageGroup: '6-7', subject: 'science', title: 'Light and Shadow', description: 'How shadows are formed', skill: 'Optics', tags: ['Level 2'], prerequisites: [], difficulty: 'abstract', montessoriArea: 'Cultural', cambridgeStrand: 'Physics', activities: [{ id: 'act-sci-l7', type: 'experiment', instructions: ['Create shadows'], successCriteria: ['Understands shadow'], componentId: 'PhysicsLab' }], assessment: { id: 'assess-sci-l7', type: 'score', masteryScore: 80 } },
  { id: 'sci-l8-sound', framework: 'cambridge-primary', ageGroup: '6-7', subject: 'science', title: 'Sound Vibrations', description: 'How sound travels', skill: 'Acoustics', tags: ['Level 2'], prerequisites: [], difficulty: 'abstract', montessoriArea: 'Cultural', cambridgeStrand: 'Physics', activities: [{ id: 'act-sci-l8', type: 'explore', instructions: ['Explore vibrations'], successCriteria: ['Understands sound'], componentId: 'PhysicsLab' }], assessment: { id: 'assess-sci-l8', type: 'score', masteryScore: 80 } },

  // --- LEVEL 3: Earth Science & Materials ---
  { id: 'sci-l9-rocks', framework: 'cambridge-primary', ageGroup: '7-8', subject: 'science', title: 'Rocks and Minerals', description: 'Explore different rocks', skill: 'Geology', tags: ['Level 3'], prerequisites: [], difficulty: 'concrete', montessoriArea: 'Cultural', cambridgeStrand: 'Earth Science', activities: [{ id: 'act-sci-l9', type: 'identify', instructions: ['Identify rocks'], successCriteria: ['Names rocks'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-l9', type: 'score', masteryScore: 80 } },
  { id: 'sci-l10-water', framework: 'cambridge-primary', ageGroup: '7-8', subject: 'science', title: 'Water Cycle', description: 'Evaporation, condensation, and rain', skill: 'Hydrology', tags: ['Level 3'], prerequisites: [], difficulty: 'abstract', montessoriArea: 'Cultural', cambridgeStrand: 'Earth Science', activities: [{ id: 'act-sci-l10', type: 'sequence', instructions: ['Arrange water cycle'], successCriteria: ['Correct order'], componentId: 'VirtualLab' }], assessment: { id: 'assess-sci-l10', type: 'score', masteryScore: 80 } },
  { id: 'sci-l11-materials', framework: 'cambridge-primary', ageGroup: '7-8', subject: 'science', title: 'Materials and Properties', description: 'Wood, metal, glass, and plastic', skill: 'Material Science', tags: ['Level 3'], prerequisites: [], difficulty: 'concrete', montessoriArea: 'Cultural', cambridgeStrand: 'Science', activities: [{ id: 'act-sci-l11', type: 'match', instructions: ['Match materials'], successCriteria: ['Correct identification'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-l11', type: 'score', masteryScore: 80 } },
  { id: 'sci-l12-daynight', framework: 'cambridge-primary', ageGroup: '7-8', subject: 'science', title: 'Day and Night', description: 'How the Earth rotates', skill: 'Astronomy', tags: ['Level 3'], prerequisites: [], difficulty: 'abstract', montessoriArea: 'Cultural', cambridgeStrand: 'Earth Science', activities: [{ id: 'act-sci-l12', type: 'sequence', instructions: ['Learn rotation'], successCriteria: ['Understands day/night'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-l12', type: 'score', masteryScore: 80 } },

  // --- LEVEL 4: Human Body & Health ---
  { id: 'sci-l13-bodyparts', framework: 'cambridge-primary', ageGroup: '8-9', subject: 'science', title: 'Body Parts', description: 'Learn the parts of your body', skill: 'Anatomy', tags: ['Level 4'], prerequisites: [], difficulty: 'concrete', montessoriArea: 'Cultural', cambridgeStrand: 'Biology', activities: [{ id: 'act-sci-l13', type: 'identify', instructions: ['Identify body parts'], successCriteria: ['Names body parts'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-l13', type: 'score', masteryScore: 80 } },
  { id: 'sci-l14-heart', framework: 'cambridge-primary', ageGroup: '8-9', subject: 'science', title: 'The Human Heart', description: 'How your heart pumps blood', skill: 'Circulatory System', tags: ['Level 4'], prerequisites: ['sci-l13-bodyparts'], difficulty: 'abstract', montessoriArea: 'Cultural', cambridgeStrand: 'Biology', activities: [{ id: 'act-sci-l14', type: 'explore', instructions: ['Learn about heart'], successCriteria: ['Understands heart'], componentId: 'VirtualLab' }], assessment: { id: 'assess-sci-l14', type: 'score', masteryScore: 80 } },
  { id: 'sci-l15-food', framework: 'cambridge-primary', ageGroup: '8-9', subject: 'science', title: 'Healthy Eating', description: 'What foods keep you healthy?', skill: 'Nutrition', tags: ['Level 4'], prerequisites: [], difficulty: 'concrete', montessoriArea: 'Cultural', cambridgeStrand: 'Biology', activities: [{ id: 'act-sci-l15', type: 'identify', instructions: ['Select healthy foods'], successCriteria: ['Correct selection'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-l15', type: 'score', masteryScore: 80 } },
  { id: 'sci-l16-bones', framework: 'cambridge-primary', ageGroup: '8-9', subject: 'science', title: 'Skeleton and Bones', description: 'The frame that holds your body', skill: 'Skeletal System', tags: ['Level 4'], prerequisites: ['sci-l13-bodyparts'], difficulty: 'abstract', montessoriArea: 'Cultural', cambridgeStrand: 'Biology', activities: [{ id: 'act-sci-l16', type: 'identify', instructions: ['Identify bones'], successCriteria: ['Names bones'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-l16', type: 'score', masteryScore: 80 } },

  // --- LEVEL 5: Chemistry Basics & States of Matter ---
  { id: 'sci-l17-solids', framework: 'cambridge-primary', ageGroup: '9-10', subject: 'science', title: 'States of Matter: Solids', description: 'What is a solid?', skill: 'Chemistry', tags: ['Level 5'], prerequisites: [], difficulty: 'concrete', montessoriArea: 'Cultural', cambridgeStrand: 'Science', activities: [{ id: 'act-sci-l17', type: 'identify', instructions: ['Identify solids'], successCriteria: ['Correct identification'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-l17', type: 'score', masteryScore: 80 } },
  { id: 'sci-l18-liquids', framework: 'cambridge-primary', ageGroup: '9-10', subject: 'science', title: 'States of Matter: Liquids', description: 'Pourable and flowing', skill: 'Chemistry', tags: ['Level 5'], prerequisites: ['sci-l17-solids'], difficulty: 'concrete', montessoriArea: 'Cultural', cambridgeStrand: 'Science', activities: [{ id: 'act-sci-l18', type: 'identify', instructions: ['Identify liquids'], successCriteria: ['Correct identification'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-l18', type: 'score', masteryScore: 80 } },
  { id: 'sci-l19-gases', framework: 'cambridge-primary', ageGroup: '9-10', subject: 'science', title: 'States of Matter: Gases', description: 'Invisible air around us', skill: 'Chemistry', tags: ['Level 5'], prerequisites: ['sci-l18-liquids'], difficulty: 'abstract', montessoriArea: 'Cultural', cambridgeStrand: 'Science', activities: [{ id: 'act-sci-l19', type: 'identify', instructions: ['Identify gases'], successCriteria: ['Correct identification'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-l19', type: 'score', masteryScore: 80 } },
  { id: 'sci-l20-melting', framework: 'cambridge-primary', ageGroup: '9-10', subject: 'science', title: 'Melting and Freezing', description: 'Changing from solid to liquid', skill: 'Phase Changes', tags: ['Level 5'], prerequisites: ['sci-l17-solids'], difficulty: 'abstract', montessoriArea: 'Cultural', cambridgeStrand: 'Science', activities: [{ id: 'act-sci-l20', type: 'experiment', instructions: ['Learn melting'], successCriteria: ['Understands changes'], componentId: 'VirtualLab' }], assessment: { id: 'assess-sci-l20', type: 'score', masteryScore: 80 } },

  // --- LEVEL 6: Advanced Earth & Space ---
  { id: 'sci-l21-space', framework: 'cambridge-primary', ageGroup: '9-10', subject: 'science', title: 'The Solar System', description: 'Planets around our sun', skill: 'Astronomy', tags: ['Level 6'], prerequisites: [], difficulty: 'abstract', montessoriArea: 'Cultural', cambridgeStrand: 'Earth Science', activities: [{ id: 'act-sci-l21', type: 'identify', instructions: ['Learn planets'], successCriteria: ['Names planets'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-l21', type: 'score', masteryScore: 80 } },
  { id: 'sci-l22-stars', framework: 'cambridge-primary', ageGroup: '9-10', subject: 'science', title: 'Stars and Constellations', description: 'Bright lights in the night sky', skill: 'Astronomy', tags: ['Level 6'], prerequisites: [], difficulty: 'abstract', montessoriArea: 'Cultural', cambridgeStrand: 'Earth Science', activities: [{ id: 'act-sci-l22', type: 'match', instructions: ['Match constellations'], successCriteria: ['Correct matches'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-l22', type: 'score', masteryScore: 80 } },
  { id: 'sci-l23-weather', framework: 'cambridge-primary', ageGroup: '9-10', subject: 'science', title: 'Weather Patterns', description: 'Sun, rain, wind, and storms', skill: 'Meteorology', tags: ['Level 6'], prerequisites: [], difficulty: 'abstract', montessoriArea: 'Cultural', cambridgeStrand: 'Earth Science', activities: [{ id: 'act-sci-l23', type: 'identify', instructions: ['Identify weather'], successCriteria: ['Understands weather'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-l23', type: 'score', masteryScore: 80 } },
  { id: 'sci-l24-season', framework: 'cambridge-primary', ageGroup: '9-10', subject: 'science', title: 'The Four Seasons', description: 'Spring, Summer, Autumn, Winter', skill: 'Earth Science', tags: ['Level 6'], prerequisites: [], difficulty: 'concrete', montessoriArea: 'Cultural', cambridgeStrand: 'Earth Science', activities: [{ id: 'act-sci-l24', type: 'sequence', instructions: ['Learn seasons'], successCriteria: ['Correct order'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-l24', type: 'score', masteryScore: 80 } },

  // --- LEVEL 7: Ecology & Environment ---
  { id: 'sci-l25-foodchain', framework: 'cambridge-primary', ageGroup: '9-10', subject: 'science', title: 'Food Chains', description: 'Who eats who in nature', skill: 'Ecology', tags: ['Level 7'], prerequisites: [], difficulty: 'abstract', montessoriArea: 'Cultural', cambridgeStrand: 'Biology', activities: [{ id: 'act-sci-l25', type: 'sequence', instructions: ['Build food chain'], successCriteria: ['Correct order'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-l25', type: 'score', masteryScore: 80 } },
  { id: 'sci-l26-recycle', framework: 'cambridge-primary', ageGroup: '9-10', subject: 'science', title: 'Reduce, Reuse, Recycle', description: 'Protecting our planet', skill: 'Sustainability', tags: ['Level 7'], prerequisites: [], difficulty: 'concrete', montessoriArea: 'Cultural', cambridgeStrand: 'Global Perspectives', activities: [{ id: 'act-sci-l26', type: 'identify', instructions: ['Sort recyclables'], successCriteria: ['Correct sorting'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-l26', type: 'score', masteryScore: 80 } },
  { id: 'sci-l27-habitats', framework: 'cambridge-primary', ageGroup: '9-10', subject: 'science', title: 'Protecting Habitats', description: 'Why animals need safe homes', skill: 'Conservation', tags: ['Level 7'], prerequisites: [], difficulty: 'abstract', montessoriArea: 'Cultural', cambridgeStrand: 'Global Perspectives', activities: [{ id: 'act-sci-l27', type: 'explore', instructions: ['Learn conservation'], successCriteria: ['Understands habitats'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-l27', type: 'score', masteryScore: 80 } },
  { id: 'sci-l28-extinct', framework: 'cambridge-primary', ageGroup: '9-10', subject: 'science', title: 'Endangered Animals', description: 'Animals that need our help', skill: 'Conservation', tags: ['Level 7'], prerequisites: [], difficulty: 'abstract', montessoriArea: 'Cultural', cambridgeStrand: 'Global Perspectives', activities: [{ id: 'act-sci-l28', type: 'identify', instructions: ['Learn endangered animals'], successCriteria: ['Identifies threats'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-l28', type: 'score', masteryScore: 80 } },

  // --- LEVEL 8: Advanced Physics & Energy ---
  { id: 'sci-l29-electricity', framework: 'cambridge-primary', ageGroup: '9-10', subject: 'science', title: 'Electricity Basics', description: 'How circuits work', skill: 'Energy', tags: ['Level 8'], prerequisites: [], difficulty: 'abstract', montessoriArea: 'Cultural', cambridgeStrand: 'Physics', activities: [{ id: 'act-sci-l29', type: 'experiment', instructions: ['Build a circuit'], successCriteria: ['Understands circuits'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-l29', type: 'score', masteryScore: 80 } },
  { id: 'sci-l30-energy', framework: 'cambridge-primary', ageGroup: '9-10', subject: 'science', title: 'Renewable Energy', description: 'Solar, wind, and water power', skill: 'Energy', tags: ['Level 8'], prerequisites: [], difficulty: 'abstract', montessoriArea: 'Cultural', cambridgeStrand: 'Physics', activities: [{ id: 'act-sci-l30', type: 'explore', instructions: ['Learn renewable energy'], successCriteria: ['Identifies sources'], componentId: 'ScienceLab' }], assessment: { id: 'assess-sci-l30', type: 'score', masteryScore: 80 } }
];